# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

'1.19.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.linspace(7, 7, 7)

array([7., 7., 7., 7., 7., 7., 7.])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,100,2) # не включая 100

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
x = np.random.randn(10)
print(x)
x[::-1]

[ 0.89915033 -0.85223306  0.05877448  1.38877446 -1.17907606  0.47147001
 -1.27988122 -1.41673099 -1.08832361 -0.24975377]


array([-0.24975377, -1.08832361, -1.41673099, -1.27988122,  0.47147001,
       -1.17907606,  1.38877446,  0.05877448, -0.85223306,  0.89915033])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
m = 7
np.diag(range(1-m,5-m)) + m

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.full((5,5), range(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
c = np.random.randn(100).reshape(10,10)
print (c)
c - c.mean(axis=1)

[[ 0.43327809  0.80863561 -0.40418462  0.53638458  0.86528354 -0.09208598
   1.32052998 -0.56087638  0.60082575 -0.19075244]
 [ 0.04032121  0.93777238  1.06221699  0.90299968 -0.26269686 -0.62260495
   0.45225022  1.238864   -0.95381786 -0.24256407]
 [-2.21577795 -0.24958289 -0.02709342 -0.56802998  0.18096918 -0.18475371
  -0.38290384  1.70605053 -0.78979888  0.60259837]
 [-0.90035571  0.72136985  1.43644055 -0.29909932  0.49606057  0.79237074
  -1.70859425 -0.43804592 -0.01448598  0.38825493]
 [-0.063242   -1.05662789 -0.41157683 -2.21897142 -0.03238875 -0.05564872
   0.67466493  0.79277522  0.39856881  0.80781058]
 [-0.50635815  0.03358652 -0.58260171 -0.38796785  2.04908615  0.02397997
   1.35321091  1.04438691 -1.13216925 -0.29940934]
 [-1.41540376  0.88252433  1.01270864 -0.83877596 -0.30159119  0.15171353
   0.92738911  1.05792906 -0.6850173   0.15598892]
 [ 1.2117156   0.9784802   0.49963247 -0.17521231  0.2494769  -0.40899771
   2.34813817 -0.27063773 -0.62870161 -1.41386018]


array([[ 0.10157428,  0.55336154, -0.21135236,  0.48899304,  0.98174715,
        -0.2516604 ,  1.22578345, -0.79987976,  0.0810384 , -0.46103936],
       [-0.2913826 ,  0.68249831,  1.25504925,  0.85560813, -0.14623325,
        -0.78217937,  0.35750368,  0.99986062, -1.47360521, -0.51285098],
       [-2.54748177, -0.50485697,  0.16573884, -0.61542152,  0.29743279,
        -0.34432813, -0.47765038,  1.46704715, -1.30958623,  0.33231145],
       [-1.23205952,  0.46609578,  1.6292728 , -0.34649087,  0.61252417,
         0.63279632, -1.80334079, -0.6770493 , -0.53427332,  0.11796802],
       [-0.39494581, -1.31190196, -0.21874457, -2.26636297,  0.08407485,
        -0.21522314,  0.57991839,  0.55377184, -0.12121854,  0.53752367],
       [-0.83806197, -0.22168756, -0.38976945, -0.4353594 ,  2.16554975,
        -0.13559444,  1.25846437,  0.80538353, -1.6519566 , -0.56969626],
       [-1.74710758,  0.62725026,  1.2055409 , -0.88616751, -0.18512758,
        -0.00786088,  0.83264257,  0.81892568

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
c = np.random.randn(100).reshape(10,10)
print (c)
c - np.median(c, axis=0)

[[-0.13954378 -0.65116116 -0.44797965 -0.53383993  0.67420607  1.78848424
   0.9689781  -0.50801283  0.04994901  0.3769961 ]
 [ 0.15571384 -0.18624994 -0.60667587 -1.88316552 -0.40942304  0.19828544
  -0.39948799  0.21219568 -1.55709347  0.53523905]
 [ 0.01586712 -0.12960451  0.56913137  1.24777325 -0.3471631  -1.23871703
  -1.18668754 -0.42735495 -1.47296447  0.18569422]
 [ 0.78481903 -0.63037873 -0.3482208  -1.46655767 -0.80787104  0.77973548
  -0.07017505  2.17569111 -1.0499013  -0.63492652]
 [-1.25858752 -0.71376574 -2.4776445  -0.13676645  0.89693873  2.54830284
   0.60516603  0.2120311   0.06431454 -0.81866584]
 [ 1.00628231  0.78242098  1.17304875 -1.07668384 -0.07346829  0.72163088
  -0.91689789  0.46622587 -0.1470306   0.38606846]
 [-1.79224249 -0.50748387  0.15011807  2.13598435  2.37591991  0.10310907
   1.21041053  0.08544704  1.04305823  0.78067556]
 [ 2.22535982 -2.07840427 -0.700363   -1.93122987  1.05431917 -0.05386275
  -1.1764078  -1.98067936 -1.00103949  0.49825505]


array([[-0.07770545, -0.08222985, -0.34892828, -0.19853674,  0.56267444,
         1.32852608,  1.14554531, -0.6567519 ,  0.26591281, -0.00453618],
       [ 0.21755217,  0.38268136, -0.5076245 , -1.54786233, -0.52095467,
        -0.26167272, -0.22292078,  0.06345661, -1.34112968,  0.15370677],
       [ 0.07770545,  0.43932679,  0.66818273,  1.58307644, -0.45869473,
        -1.69867519, -1.01012032, -0.57609402, -1.25700068, -0.19583806],
       [ 0.84665736, -0.06144743, -0.24916944, -1.13125449, -0.91940267,
         0.31977733,  0.10639216,  2.02695204, -0.83393751, -1.0164588 ],
       [-1.19674919, -0.14483444, -2.37859313,  0.19853674,  0.7854071 ,
         2.08834469,  0.78173324,  0.06329203,  0.28027834, -1.20019812],
       [ 1.06812064,  1.35135228,  1.27210012, -0.74138065, -0.18499992,
         0.26167272, -0.74033067,  0.3174868 ,  0.06893319,  0.00453618],
       [-1.73040416,  0.06144743,  0.24916944,  2.47128753,  2.26438828,
        -0.35684909,  1.38697774, -0.06329203

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
c = np.random.randn(25).reshape(5,5)
np.concatenate((c, c.max(axis=0).reshape(-1,1)), axis=1)
np.concatenate((c, c.min(axis=0).reshape(-1,1)), axis=1)

array([[-0.81725247,  0.45072311, -0.48782984, -1.43964445,  0.32655561,
        -1.09073481],
       [ 1.01350169, -1.24706887, -0.56838471,  0.02938367,  1.17271101,
        -1.24706887],
       [ 0.70864564,  0.18963177, -0.38782678, -0.43580992, -1.06231182,
        -0.81623207],
       [ 1.39295015, -0.37569102,  0.93523552,  1.16513083,  1.14009686,
        -1.66614561],
       [-1.09073481,  0.63014401, -0.81623207, -1.66614561, -0.2114295 ,
        -1.06231182]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [ ]:
x = np.arange(1,51,1)
x1 = x[::2].copy().reshape(-1,1) # нечет
x2 = x[1::2].copy().reshape(1,-1) # чет

z = np.dot(x2, x1)
print(x1.shape, x2.shape, z.shape)
print(z)
try:
  print(np.linalg.inv(z))
except np.linalg.LinAlgError as lae:
  print('Определитель 0')

(25, 1) (1, 25) (1, 1)
[[21450]]
[[4.66200466e-05]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [ ]:
x = np.zeros(64).reshape(8,8)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])